ref: simplify flattenTree
numtide/flake-utils pull request #29
Opened 2021-04-11 17:19 UTC by blaggacao

People have been complaining of the readability of the code. In particular, the former `flattenTreeSystem` which might have ultimately lead to its abandonment instead of its fixing in the particular context it was abandoned.

Do a preemptive strike, here.

2021-04-12 09:32 UTC, zimbatm commented on flattenTree.nix
> -      sum
Line 14 assumes that the value is a derivation so removing this check will fail.

Both 11 and 18 assume that it's a derivation so I packed the check here. For readability, it would be ok to remove that micro-optimization.

2021-04-12 09:33 UTC, zimbatm commented
I think we should get rid of `flattenTree`. It's not providing a lot of value, except using `packages` instead of `legacyPackages`.

2021-04-12 15:02 UTC, blaggacao commented
I think the name-spacing by "/" can proove useful in itself and sets a good precedent. I have a sense it will be useful to export `self.overlays` with a flat keyspace that requires to include a composed key out of name + some other concept(s).

Though, the isDerivation check, as (now) assumed by filterPackages, maybe is in a dead spot, indeed, and could be removed cheaply.

2021-04-12 18:00 UTC, zimbatm commented
I guess it doesn't hurt to keep it.

2021-04-13 23:16 UTC, blaggacao commented on flattenTree.nix
> -      sum
I guess with `filterPackages` as a convenience function which filters on flattened result for _valid_ packages, that is, _also_ derivations, we can omit the isDerivation check here alltogether and make flattentree a generally useful tree flattener, which is still a nice concept.

I'll amend this PR accordingly and point to a use case, afterwards.

Compat wise, I'm not sure what would be the best transition to that end, in case we agree on the design.

2021-04-13 23:31 UTC, blaggacao commented on flattenTree.nix
> +  isAttrs = builtins.isAttrs or (builtins.typeOf val) != "set";
```suggestion
  isAttrs = builtins.isAttrs or (builtins.typeOf val) == "set";
```

2021-04-13 23:34 UTC, blaggacao commented on flattenTree.nix
> -      sum
The `isDerivation` would concatenate both checks and for line 18, I think we would be good? (dropping that micro-optimization)
```
nix-repl> a = [ ]
nix-repl> if a ? b then a.b else "boom"
"boom"
```

2022-06-23 18:35 UTC, sigprof requested changes

2022-06-23 18:35 UTC, sigprof commented on flattenTree.nix
> +  isAttrs = builtins.isAttrs or (builtins.typeOf val) == "set";
This polyfill looks useless (blame on Nix docs shows that `builtins.isAttrs` was there 15 years ago, while `builtins.typeOf` was added only 9 years ago).

2023-04-09 10:53 UTC, zimbatm commented
Closing as flattenTree is stable, and I don't want to touch it too much

2023-04-09 10:53 UTC, closed without merging